apiVersion: v1
kind: Service
metadata:
  name: backend-api
  labels:
    service: api
    env: {{ .Values.env }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    service: api
    env: {{ .Values.env }}
    component: backend
