apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: gcr.io/gcore-dev01/grpc-server
      context: grpc-server
    - image: gcr.io/gcore-dev01/http-server
      context: http-server
  googleCloudBuild:
deploy:
  helm:
    releases:
      - name: grpc-server
        chartPath: grpc-server/helm
        wait: true
        valuesFiles:
          - grpc-server/helm/values.yaml
            #        values:
          #          image: skaffold-helm
          #recreatePods will pass --recreate-pods to helm upgrade
        recreatePods: true
          #overrides builds an override values.yaml file to run with the helm deploy
          #overrides:
          # some:
          #   key: someValue
          #setValues get appended to the helm deploy with --set.
        #setValues:
        #some.key: someValue
      - name: http-server
        chartPath: http-server/helm
        wait: true
        valuesFiles:
          - http-server/helm/values.yaml
        recreatePods: true