#https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: chrisge-net
#  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: chrisge-net-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  #  organization:
  #    - jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  #  commonName: example.com
  #  isCA: false
  #  keySize: 2048
  #  keyAlgorithm: rsa
  #  keyEncoding: pkcs1
  #  usages:
  #    - server auth
  #    - client auth
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
    - chrisge.net
    - www.chrisge.net
  #  uriSANs:
  #    - spiffe://cluster.local/ns/sandbox/sa/example
  #  ipAddresses:
  #    - 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
#    group: cert-manager.io